"""test

Revision ID: 32fc9127ccbf
Revises: eb14a05ef754
Create Date: 2023-05-15 01:07:17.262712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fc9127ccbf'
down_revision = 'eb14a05ef754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('submitted_answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_answer', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
